apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-app-deployment
  labels:
    app: credit-card
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-card
  template:
    metadata:
      labels:
        app: credit-card
    spec:
      containers:
        - name: credit-card
          image: rnstphns/credit-card:latest
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-app-service
spec:
  type: NodePort
  selector:
    app: credit-card
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30200
