apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-database-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
  
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - image: mysql
          name: customer
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secret
                  key: customer_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key: customer_name
          # resources:
          #   limits:
          #    memory: "256Mi"
          #    cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30010