apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deployment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: rnstphns/payment-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: payment_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: payment_password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: payment_url
          resources:
            limits:
             memory: "256Mi"
             cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-app-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30500
