apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-database-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: mysql
          name: payment
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: payment_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: payment_name
          resources:
            limits:
             memory: "256Mi"
             cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30012