apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: rnstphns/order-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: order_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: order_password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: order_url
          resources:
            limits:
             memory: "256Mi"
             cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-app-service
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      nodePort: 30004
