apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-app-deployment
  labels:
    app: paypal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paypal
  template:
    metadata:
      labels:
        app: paypal
    spec:
      containers:
        - name: paypal
          image: rnstphns/paypal:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: paypal-app-service
spec:
  type: NodePort
  selector:
    app: paypal
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30600
