apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-app-deployment
  labels:
    app: shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: rnstphns/shipping-app:latest
          ports:
            - containerPort: 8088
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shipping-secret
                  key: shipping_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shipping-secret
                  key: shipping_password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: shipping_url
          resources:
            limits:
             memory: "512Mi"
             cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-app-service
spec:
  type: NodePort
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30800
