apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-database-deployment
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - image: mysql
          name: shipping
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shipping-secret
                  key: shipping_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: shipping-config
                  key: shipping_name
          resources:
            limits:
             memory: "512Mi"
             cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: NodePort
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30014